### ISSUE TITLE
Not working in Yii2

### ISSUE THREAD

**Issue by eugenyh** [makroxyz/yii2-wizard#3]
Trying to use this extension in my project.

Controller:

<pre>

public function actionNew($step=null)  //new must start the wizard
    {
        If ($step=='reset') {
            $this->reset();
            $step=null;
        }
        $this->process($step);
    }
...
 public function behaviors() 
    {
        return array(
            'wizard'=>array(
            'class'=>'makroxyz\wizard\WizardBehavior',
            'autoAdvance' => false,
            'steps'=>array(
                       'Begin'=>'BeginStep',
                       'Questions'=>'QuestionStep',
                          ),
            )
        );
    }
...
 public function WizardProcessStep($event) 
    {
        $modelName = "frontend\models\\".ucfirst($event->step);
        $model = new $modelName();
        $model->attributes = $event->data;

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                 $event->sender->save($model->attributes);
                 $event->handled = true; 
        }
        else {
                 return $this->render($event->step, compact('event','model'));
        }
    }

</pre>

My view (at the fist step = BeginStep.php)

<pre>

/?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

$this->title = 'Step #1';
$this->params['breadcrumbs'][] = $this->title;

$event->sender->menu->run();
?/
/div class="bw"/
    /h1//?= Html::encode($this->title) ?///h1/

    /p/Please fill out the following fields to signup://p/

    /div class="row">
       /div class="col-lg-5">
            /?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
                /?= $form->field($model, 'estatus') ?>
                /?= $form->field($model, 'number') ?>
                /?= $form->field($model, 'post_date')->passwordInput() ?>
                /div class="form-group">
                    /?= Html::submitButton('Next step >>', ['class' => 'btn btn-primary', 'name' => 'next-step-button']) ?>
                //div>
            /?php ActiveForm::end(); ?>
        //div>
    //div>
//div>

</pre>

NOTE: i was change < sing to / for correct view in github.

So, there is nothing out to the screen!
Totaly nothing. No errors, no text. Empty.

**Comment by makroxyz** [comment]
Check namespaces in your files. Let me know

**Comment by eugenyh** [comment]
So cheked namespace. All fine
model have: namespace frontend\models;
controller have: namespace frontend\controllers;
view have no namespace

all as usual.

But its very strange. When I change string

<pre>
                 return $this->render($event->step, compact('event','model'));
</pre>

to

<pre>
                 echo $this->render($event->step, compact('event','model'));
</pre>

in controllers:

<pre>
public function WizardProcessStep($event) 
    {
        $modelName = "frontend\models\\".ucfirst($event->step);
        $model = new $modelName();
        $model->attributes = $event->data;
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                 $event->sender->save($model->attributes);
                 $event->handled = true; 
        }
        else {
                 return $this->render($event->step, compact('event','model'));
        }
    }
</pre>

The page is rendered. But it is not good.
It cannot be so...

**Comment by makroxyz** [comment]
Try now... and let me know. Mine it's just a port not fully tested so thanks for your help

**Comment by eugenyh** [comment]
no, nothing changed.
still the same

**Comment by makroxyz** [comment]
OK, wizardProcessStep is an event handler.
so it isn't an action and return something does not render anything. I think you must change response content

``` php
Yii::$app->getResponse()->content = $this->render($event->step, compact('event','model'));
```

**Comment by eugenyh** [comment]
yes,  it isn't an action but I using this wizard in my previous project at Yii 1, and all works fine.
By the way - this project is translation of my old project to Yii2 :)

and another moment:
with 

<pre>
Yii::$app->getResponse()->content = $this->render($event->step, compact('event','model'));
</pre>

and the same as

<pre>
echo $this->render($event->step, compact('event','model'));
</pre>

I see rendered BeginStep.php but without steps menu:

<pre>
$event->sender->menu->run();
</pre>

Changing this line to:

<pre>
echo $event->sender->menu->run();
</pre>

Menu is rendered....

It is all very strange. Seems to be it is missing something...
Will thinking.

**Comment by makroxyz** [comment]
You really did an amazing job!!
So you're the best help to improve that behavior!

I've ported the extension in a day 'cos I need it in a little project... I haven't time to do a deep test
